project:
  type: book
  output-dir: docs

book:
  title: "Lab Manual: DSA 554 3.0 Spatio-temporal Data Analysis"
  author: "Thiyanga S. Talagala"
  date: "Last updated 06/01/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - chap2.qmd
    - chap3.qmd
    - chap4.qmd
    - chap5.qmd
    - chap6.qmd
    - chap7.qmd
    - references.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

